### ISSUE TITLE
Timeout on suspend/standby

### ISSUE THREAD

**Issue by ChrisS85** [negativo17/xpad-kmod#1]
First of all, thanks for this driver!

I'm using a wireless XBOX360 gamepad with an USB receiver.
When putting the system into standby I'm seeing a 20s delay until the PC goes into standby completely.

I'm seeing the following dmesg log entries which pointed me to this driver:
```
[29186.371566] xpad 1-3:1.6: timed out waiting for output URB to complete, killing
[29191.491505] xpad 1-3:1.4: timed out waiting for output URB to complete, killing
[29196.611429] xpad 1-3:1.2: timed out waiting for output URB to complete, killing
[29201.731378] xpad 1-3:1.0: timed out waiting for output URB to complete, killing
```

This is logged in `static void xpad_stop_output(struct usb_xpad *xpad)` which is likely called from `static int xpad_suspend(struct usb_interface *intf, pm_message_t message)`.

This behavior only occurs when the gamepad is powered off, so my suspicion is that the driver is trying to turn it off but isn't getting a response from the gamepad and thus runs into the timeout.

I've tried setting the auto_poweroff parameter to 0 and this fixes the delay, however I fear that this might cause battery drain when the gamepad is on while suspending. Iit goes innto an "uncoupled" mode where all 4 ring LEDs are blinking. Maybe it'd turn off later, I haven't checked that yet.

Anything I can do to help debug this issue?
lsusb gives the following info if that helps:
> Bus 001 Device 003: ID 045e:0719 Microsoft Corp. Xbox 360 Wireless Adapter

Possible ideas:
- Decrease the timeout to 1 s or so (maybe find a way to parallelize the 4 timeouts I'm seeing in series to decrease total wait time)
- If possible, send the command without waiting for its result. I see you're killing the urb anchor on timeout, maybe it's possible to do this after wakeup or use a different function such as usb_unlink_anchored_urbs()? I have no experience with usb drivers, so just guessing.
- Track online state of the gamepad somehow, only turn it off when it is deemed online?

**Comment by scaronni** [comment]
Hi, this repository has been updated last time 7 years ago, the `xpad` driver in the linux kernel is already containing everything that's here. You should use xone or xpadneo for your controller:

https://negativo17.org/xbox-series-xs-wireless-controller-in-fedora-steam/

Same logic for both Bluetooth (`xpadneo` or wired / wifi dongle support `xone`). Just install them both and you should be fine:
```
dnf install akmod-xpadneo akmod-xone
```
or:
```
dnf install dkms-xpadneo dkms-xone
```

**Comment by scaronni** [comment]
Btw, I've stopped shipping RPMs for this I guess at least 4 years ago, but I'm not entirely sure. You should definitely not use it.

**Comment by ChrisS85** [comment]
Seems I missed that yesterday, I simply assumed it was the correct code since I didn't see any fork of this project, found the log string and the behavior matched my interpretation of this code. I'm on Debian btw. for what it's worth, I'll check which version of the driver I'm actually using. Thanks anyway!

**Comment by ChrisS85** [comment]
Just for reference, the linux kernel provided by debian (6.1.0-0.deb11.17-amd64 as of now) includes a newer version of this driver but the parts of the source code that lead to the problem described above seem to be unchanged.

I will follow your advice and try one of the other drivers.
